### ISSUE TITLE
Creating a new instance without filling all property fields leads to "internal server error"

### ISSUE THREAD

**Issue by marek-dudas** [AKSW/OntoWiki#274]
When submitting the Create New Instance dialog: if some property fields are left blank “error while post request: Internal Server Error” is displayed. The instance is created correctly although. In some cases it takes several minutes before the error is displayed.
If the blank property fields are removed from the dialog, everything works and no error is displayed.

Happens on the following configuration:
Ubuntu 12.04.4
Virtuoso Opensource 07.00.3203 
PHP 5.4.22-1+debphp.org~precise+1
Erfurt & RDFauthor: latest git versions as of 11-20-2013
Ontowiki 0.9.11 git (as of 11-20-2013)

**Comment by roland-c** [comment]
This bug is still in there; when I create certain resources in my OntoWIki install I need to remove all
l empty fields in the data entry box before being able to save the resource. If there are empty fields in 
the box when saving the resource I get the Internal Server Error:

2015-10-12T09:34:42+02:00 EMERG (0): Erfurt_Store_Adapter_Exception: SPARQL Error: [unixODBC][OpenLink][Virtuoso iODBC Driver][Virtuoso Server].....: Empty string is not a valid argument to iri_to_id (), type 182 ()

So I guess something is going wrong in the generation of the URI based on the fields entered (?)

**Comment by white-gecko** [comment]
Hey roland,
this issue should be fixed in the amsl branch.
@splattater Could you please try to find the according commit and try to apply this fix to the main/develop branch?

**Comment by white-gecko** [comment]
This might be the commit: https://github.com/amsl-project/RDFauthor/commit/7816a48beb3444c659360c88b41bd817e837e932

**Comment by roland-c** [comment]
Hi Nate, Thanks man!

On 14-10-15 17:20, Natanael Arndt wrote:
>
> This might be the commit: amsl-project/RDFauthor@7816a48 
> <https://github.com/amsl-project/RDFauthor/commit/7816a48beb3444c659360c88b41bd817e837e932>
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/AKSW/OntoWiki/issues/274#issuecomment-148082521>.
>

-- 
Signature Metamatter/Roland Cornelissen
metamatter*| *Drs. Roland Cornelissen*| *Weersterweg 12*| *9832TE*| *Den 
Horn*| *T +31 (0)50 5515369*| *M +31 (0)6 14797518*| *www.metamatter.nl 
<http://www.metamatter.nl>

**Comment by white-gecko** [comment]
@splattater this commit only seams to be part of the solution. Could you check this as well and maybe find some other solution?

**Comment by splattater** [comment]
I merged 3ff276d5dac3aeee0f7d6c59923d3f8d803b47dd the proposed workaround from @Matthimatiker 
Please reopen if the issue still exists.
