### ISSUE TITLE
XML Export for single Resources has too many triples

### ISSUE THREAD

**Issue by shinobu** [AKSW/OntoWiki#380]
Exporting single triples per XML has too many triples. My example resource had 3 triples and the other export function had only 3. The XML export has 39.

**Comment by shinobu** [comment]
Examples would be 

[Examples.zip](https://github.com/AKSW/OntoWiki/files/537449/Examples.zip)

While the first example has the correct amount of tuples, the second doesn't

it seems as if this problem is size related

**Comment by white-gecko** [comment]
Actually there is not problem at all, if an export of a resource contains more triples. Its only a problem, if the export doesn't contain all intended triples. In this case of your second resource (`http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/instances/ProductType2`)  the export also exports all the incoming edges, resp. inverse relations. I would even consider this behavior as "more correct", since the description of a resource consists of the complete context, incoming and outgoing edges.

Maybe you open a feature request for that we also export incoming edges with the other serializations.
